name: async_preferences
description: A Flutter plugin designed for asynchronous management of local preferences, primarily focused on Android and iOS platforms.
version: 0.8.0
homepage: https://davidserrano.io/
repository: https://github.com/svprdga/async_preferences

environment:
  sdk: '>=3.1.0 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: 2.3.0

flutter:
  plugin:
    platforms:
      android:
        package: com.svprdga.async_preferences
        pluginClass: AsyncPreferencesPlugin
      ios:
        pluginClass: AsyncPreferencesPlugin